### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#1]
An admin login feature for the manager who can check every user's attendance.

**Comment by amdpt323** [comment]
can i get this issue assigned

**Comment by Nikhil636** [comment]
> can i get this issue assigned

You can start the work and do share your email so that I can add you in the firebase project.

**Comment by amdpt323** [comment]
so my gmail is vamshiraina69@gmail.com kindly add me in the firebase project

**Comment by amdpt323** [comment]
also do we have any figma file so that I could follow that or its up on me that I have to create a login page

**Comment by Nikhil636** [comment]
> also do we have any figma file so that I could follow that or its up on me that I have to create a login page

Its up to you, there is no figma file.

**Comment by Gun2902** [comment]
can u assign me this isssue?

**Comment by sagnik-sanyal** [comment]
I can take up this issue to implement role based login using riverpod by writing appropriate functions after the PR #32 is merged under JWOC. Hey @Nikhil636 i can start as my PR is merged

**Comment by sarkartanmay393** [comment]
@Nikhil636 I would like to implement it under JWOC

**Comment by sagnik-sanyal** [comment]
Hey there @Nikhil636  admin login PR is added
