### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by tmsagarofficial** [Nikhil636/Attendance-app#10]
I wanted to let u know that I wanted to work on this issue of updating the Readme.md and also make it more attractive.

Also I would like to let u know that I will be up to work on creating a CODE_OF_CONDUCT.md for this project too as a seperate issue

Let e know about this issue . :)

**Comment by Namya13Jain** [comment]
I want to work on this issue under JWOC

**Comment by tmsagarofficial** [comment]
i can start working on this right ? @Nikhil636

**Comment by Nikhil636** [comment]
> i can start working on this right ? @Nikhil636

Yes you can start the work

**Comment by tmsagarofficial** [comment]
@Nikhil636 Thanks
