### ISSUE TITLE
QR code Scanner

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#2]
A scanning feature to mark attendance.

**Comment by bcsamrudh** [comment]
I would like to contribute to this.
Open Source Program: JWOC 2023

**Comment by Nikhil636** [comment]
> I would like to contribute to this. Open Source Program: JWOC 2023

You can start the work and do share your email so that i can add you to the firebase project

**Comment by bcsamrudh** [comment]
samrudhbc@gmail.com

**Comment by sagnik-sanyal** [comment]
I can work on this issue under JWOC to make a QR code scanner page to help scan qr codes
