### ISSUE TITLE
[DOC] Update Readme file new features

### ISSUE THREAD

**Issue by Suryansh1720001** [Nikhil636/Attendance-app#20]
Hello admin

## Features I want to add - 
- add the contribution guidelines.
- Add the maintainer details
- Add new features for more attractiveness
- Add the contributors details.

These are important features of the readme file of any open-source project. kindly assign me this issue.

**Comment by Nikhil636** [comment]
Can you also add the screenshot of the project?

**Comment by Suryansh1720001** [comment]
Yes, I can add the screenshot of the project. But @Nikhil636 you have to send me the screenshot. You can Upload them in google drive and give me the link here or in the discord channel. 
I will add them.
And yeah, for this - kindly change the label to hard.

**Comment by Suryansh1720001** [comment]
@Nikhil636 
Any updates about screenshot link or label ?

**Comment by Nikhil636** [comment]
Clone the project and run, Take the screenshot and upload it by yourself

> @Nikhil636 Any updates about screenshot link or label ?

**Comment by Khushal747** [comment]
i cloned the app i can add ss and update readme can you assign this work to me please

**Comment by Khushal747** [comment]
i updated readme #20 under JWOC ,also raised pull request please check
