### ISSUE TITLE
Update contribution guidelines 

### ISSUE THREAD

**Issue by anamikarawat2305** [Nikhil636/Attendance-app#26]
I want to update contribution guidelines and make a separate file for this name as Contribution.md under jwoc.

**Comment by anamikarawat2305** [comment]
@Nikhil636 I have done with this part can you check it out and merge it. also I have to do some small changes in README file can I do that?

**Comment by Nikhil636** [comment]
Yes you can do it, and do remove the TODO section from it

**Comment by anamikarawat2305** [comment]
@Nikhil636  check PR 28 and 29
