### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by tmsagarofficial** [Nikhil636/Attendance-app#37]
I would love to work on updating the `README.md` and do the following changes.

- update the screenshots of the project to those of higher quality and ones with better visibility.
- also will try to include the logo / button for each of the tech stack used part

pls let me know about the same .. i would love to work on this under jwoc

**Comment by tmsagarofficial** [comment]
Hey @Nikhil636 PLs check im not able to see the sign up option in the app..........tried on both android studio and on my mobile tooo...........

![1](https://user-images.githubusercontent.com/110724849/222536296-1e181578-b9bb-4f11-b9c4-c5f08f1d381e.png)

**Comment by khushimarothi** [comment]
I want to work on this issue
