### ISSUE TITLE
Location Saving

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#4]
Storing the location of the user in firestore database when checked in.

**Comment by aadityaagrawal** [comment]
Please assign this issue to me

**Comment by Nikhil636** [comment]
send me your email id, i'll give you the access to the firebase project

**Comment by aadityaagrawal** [comment]
adityakuagrawal@gmail.com

**Comment by sagnik-sanyal** [comment]
Hey @Nikhil636  there i am ready to work on this issue but i need a brief about this feature. Can you arrange for a discussion?

**Comment by Nikhil636** [comment]
> Hey @Nikhil636 there i am ready to work on this issue but i need a brief about this feature. Can you arrange for a discussion?

Whenever the user will check in and check out, his location will be saved in the filestore database and will also be displayed on the screen. You can take reference from here shorturl.at/GI058
