### ISSUE TITLE
Add Login with Phone number option 

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#6]

**Comment by radar101** [comment]
I would like to work under this issue as a part of JWOC.

**Comment by Khushal747** [comment]
hello ,i would like to work under this issue, please assign me this issue.

**Comment by Nikhil636** [comment]
> hello ,i would like to work under this issue, please assign me this issue.

You can start the work

**Comment by Khushal747** [comment]
thankyou

**Comment by Khushal747** [comment]
Hi Nikhil,

I'm contributing to Attendence_app, and I need to access the Firebase project to get the app ID and other configuration settings. Can you please provide me with guidance on how to access the Firebase project, or let me know if there's a separate Firebase project set up specifically for development purposes?

**Comment by Nikhil636** [comment]
Give your email , i'll give you access to the firebase project

**Comment by Khushal747** [comment]
khushal7477@gmail.com

**Comment by sagnik-sanyal** [comment]
Hey @Nikhil636  i can take up this issue under JWOC. i have already done these kinds of things before and will finsih asap
