### ISSUE TITLE
Sign up screen for creating new accounts

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#8]

**Comment by sagnik-sanyal** [comment]
I want to work on this issue under JWOC.                                                                                                                                           I can work on designing of the signup screen where the user will be able to create new accounts with state management using riverpod or provider although provider will be easier to understand for other people who are beginners and those who are working, whereas riverpod offers much more functionality than the traditional provider package.

**Comment by Nikhil636** [comment]
You can start the work and do share your email so that I can give you access to firebase project.

**Comment by sagnik-sanyal** [comment]
@Nikhil636 My email sagniksanyal1502@gmail.com

**Comment by sagnik-sanyal** [comment]
@Nikhil636 Also do you have any reference ui for signup screen or do i have to design it from scratch on figma ?

**Comment by Nikhil636** [comment]
> @Nikhil636 Also do you have any reference ui for signup screen or do i have to design it from scratch on figma ?

There is no figma file. You have to design it from scratch , you can take reference from the login screen UI.

**Comment by sagnik-sanyal** [comment]
@Nikhil636 https://www.figma.com/file/wu0m9lsvN75WRnZPxKFiSo/Attendance-app?node-id=0%3A1&t=xgbpkFDKFllpVoa1-1 can you have a look at this whether you like this design or not. Also it would be great if you could lemme know what all parameters do you need from the user while signup

**Comment by Nikhil636** [comment]
Yeah its good , you can also use labels instead of field title
And sign-up screen should have UserId, full name, Email, password, confirm password  . Each textform field should contain validators . And these data will get stored in the database except password. And will be use for login

**Comment by sagnik-sanyal** [comment]
hey @Nikhil636  can you please elaborate regarding the user id part , how the person will create their userid it is automatically generated during signup with firebase. Firebase signup is working fine as of now but the user id part is not clear to me

**Comment by Nikhil636** [comment]
> hey @Nikhil636 can you please elaborate regarding the user id part , how the person will create their userid it is automatically generated during signup with firebase. Firebase signup is working fine as of now but the user id part is not clear to me

just leave that userid part,

**Comment by sagnik-sanyal** [comment]
> > hey @Nikhil636 can you please elaborate regarding the user id part , how the person will create their userid it is automatically generated during signup with firebase. Firebase signup is working fine as of now but the user id part is not clear to me
> 
> just leave that userid part,

Pls can you try to check the PR , if it's okay you can merge it so that i can work on further part of the application

**Comment by Nikhil636** [comment]
Can you please send the pr again I forgot to add labels

**Comment by sagnik-sanyal** [comment]
Oh ok

**Comment by sagnik-sanyal** [comment]
@Nikhil636 but the thing is my branch will be outdated from my end and it might cause conflicts as you have already merged some PRs. What to do now ?

**Comment by Nikhil636** [comment]
I have added the labels on your pr so there's no problem.

**Comment by sagnik-sanyal** [comment]
Ok i have resent the new pr but if you have alredy merged the code i am unable to find the updated code with riverpod signup flow in your repository main branch @Nikhil636
