### ISSUE TITLE
Remove all the bugs that code contain

### ISSUE THREAD

**Issue by Nikhil636** [Nikhil636/Attendance-app#9]
Make the code more stable and easy to understand.

**Comment by Aniket-011** [comment]
I want to work on this issue please assign me this issue.

**Comment by AnubhaSharma2709** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue under JWOC

**Comment by Nikhil636** [comment]
> I want to work on this issue under JWOC

You can start the work.

**Comment by sagnik-sanyal** [comment]
I think this work is left pending for many days , i am not sure but as far as i remember i refactored the code in my PR #17 , if there's anything left pls inform @Nikhil636  and lets close this simple issue.  I am ready to contribute under JWOC but before that can you pls check if there's anything that needs to be refactored left ?

**Comment by Nikhil636** [comment]
I don't think there's anything left to refactor, I'm closing this issue you can claim any other issue

> I think this work is left pending for many days , i am not sure but as far as i remember i refactored the code in my PR #17 , if there's anything left pls inform @Nikhil636 and lets close this simple issue. I am ready to contribute under JWOC but before that can you pls check if there's anything that needs to be refactored left ?
